### ISSUE TITLE
Import error TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by christopherpickering** [Freely-Given-org/BibleOrgSys#26]
Hi! I'm trying to use this package with the Biblelator and getting an error:

```
Traceback (most recent call last):
  File "/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/projects/BiblelatorFiles/Biblelator/Biblelator.py", line 49, in <module>
    from BibleOrgSys import BibleOrgSysGlobals
  File "/3.9.0/lib/python3.9/site-packages/BibleOrgSys/BibleOrgSysGlobals.py", line 1408, in <module>
    def setVerbosity( verbosityLevelParameter: str | int ) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
https://github.com/Freely-Given-org/BibleOrgSys/blob/429ac756c45e32f1fd579edd148d5c2c9c010f02/BibleOrgSys/BibleOrgSysGlobals.py#L1408

I'm thinking this line should be:

```py
def setVerbosity( verbosityLevelParameter: Union[str, int] ) -> None:
```

**Comment by RobH123** [comment]
Hi there. What Python version are you running? ('python3 --version' shows 3.10.4 on my Ubuntu laptop). I think that syntax came in with v3.10 IIRC.

**Comment by christopherpickering** [comment]
Hi Rob, Ah, nice, I was in 3.9. I'll give it a shot in 3.10. Thats some new fancy syntax for python 😀
